//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPTaxiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int id_Заказы { get; set; }
        public Nullable<int> id_Автомобили { get; set; }
        public Nullable<int> id_Клиенты { get; set; }
        public Nullable<int> id_Тарифы { get; set; }
        public string Откуда { get; set; }
        public string Место_отправления { get; set; }
        public string Время_начала_заказа { get; set; }
        public string Время_окончания_заказа { get; set; }
        public string Время_заказа { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<double> Путь_в_км { get; set; }
        public string Статус_заказа { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<bool> Багаж { get; set; }
        public string Выбор_оплаты { get; set; }
        public Nullable<bool> Ожидание { get; set; }
        public int Оценка_за_обслуживание { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Тарифы Тарифы { get; set; }
    }
}
