//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPTaxiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Модель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Модель()
        {
            this.Автомобили = new HashSet<Автомобили>();
        }
    
        public int id_Модель { get; set; }
        public string Модель1 { get; set; }
        public string Марка { get; set; }
        public string Цвет { get; set; }
        public string Год { get; set; }
        public string Тип_кузова { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Автомобили> Автомобили { get; set; }
    }
}
