//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPTaxiApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тарифы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тарифы()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int id_Тарифы { get; set; }
        public string Название_тарифа { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Стоимость_за_км { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
